//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// MFCVibeDemo.rc에서 사용
//
#define IDR_MAINFRAME					128
#define IDM_ABOUTBOX					0x0010
#define IDD_ABOUTBOX					100
#define IDS_ABOUTBOX					101
#define IDD_MFCVIBEDEMO_DIALOG				102
#define IDD_ETC_STYP					103
#define IDD_BUILDING_CONTROL			104

// Dialog controls for IDD_ETC_STYP
#define IDC_WG_CMD_STATIC0				1000
#define IDC_ETC_PC_ST_3D				1001
#define IDC_ETC_PC_ST_XZ				1002
#define IDC_ETC_PC_ST_YZ				1003
#define IDC_ETC_PC_ST_XY				1004
#define IDC_ETC_PC_ST_RZ				1005
#define IDC_WG_CMD_STATIC1				1006
#define IDC_ETC_PC_MASS_TYPE2			1007
#define IDC_ETC_PC_CONSIDER_OFFSET_CHK	1008
#define IDC_ETC_CONSIDER_ROT_RIGID_MPF_CHK	1009
#define IDC_ETC_PC_MASS_TYPE3			1010
#define IDC_ETC_PC_CONVERT_SELFWEIGHT_CHK	1011
#define IDC_ETC_PC_STRUCT_MASS			1012
#define IDC_ETC_PC_STRUCT_MASS2			1013
#define IDC_ETC_PC_STRUCT_MASS3			1014
#define IDC_WG_CMD_STATIC2				1015
#define IDC_ETC_PC_GRAV					1016
#define IDC_ETC_PC_GRAV_UNIT			1017
#define IDC_WG_CMD_STATIC3				1018
#define IDC_ETC_PC_TEMP					1019
#define IDC_ETC_PC_TEMP_UNIT			1020
#define IDC_ETC_PC_ALIGN_BEAM_CHK		1021
#define IDC_ETC_PC_ALIGN_SLAB_CHK		1022

// Dialog controls for IDD_BUILDING_CONTROL
#define IDC_BC_USE_GROUND_LEVEL_CHK		1023
#define IDC_BC_GROUND_LEVEL_EDIT		1024
#define IDC_BC_GROUND_LEVEL_UNIT		1025
#define IDC_BC_CONSIDER_UNDERGROUND_CHK	1026
#define IDC_BC_BEDROCK_LEVEL_EDIT		1027
#define IDC_BC_BEDROCK_LEVEL_UNIT		1028
#define IDC_BC_CONSIDER_MASS_CHK		1029
#define IDC_BC_STORY_SHEAR_FORCE_CHK	1030
#define IDC_BC_CONSIDER_WIND_SEISMIC_CHK 1031
#define IDC_BC_ECCENTRICITY_CHK			1032
#define IDC_BC_USE_MASS_RADIO			1033
#define IDC_BC_USE_AXIAL_FORCE_RADIO	1034
#define IDC_BC_USE_SHEAR_FORCE_RADIO	1035
#define IDC_BC_LOAD_CASE_COMBO			1036
#define IDC_BC_LOAD_CASE_BTN			1037
#define IDC_BC_SCALE_FACTOR_EDIT		1038
#define IDC_BC_LOAD_CASE_LIST			1039
#define IDC_BC_ADD_BTN					1040
#define IDC_BC_MODIFY_BTN				1041
#define IDC_BC_DELETE_BTN				1042
#define IDC_BC_X_LOAD_CASE_COMBO		1043
#define IDC_BC_X_LOAD_CASE_BTN			1044
#define IDC_BC_Y_LOAD_CASE_COMBO		1045
#define IDC_BC_Y_LOAD_CASE_BTN			1046
#define IDC_BC_STORY_RESPONSE_CHK		1047
#define IDC_BC_STORY_CENTER_RADIO		1048
#define IDC_BC_STORY_AVERAGE_RADIO		1049
#define IDC_BC_STORY_DRIFT_CHK			1050

// 다음은 새 개체에 사용할 기본값입니다.
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE	130
#define _APS_NEXT_CONTROL_VALUE		1051
#define _APS_NEXT_SYMED_VALUE		101
#define _APS_NEXT_COMMAND_VALUE		32771
#endif
#endif
