//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// MFCVibeDemo.rc에서 사용
//
#define IDR_MAINFRAME					128
#define IDM_ABOUTBOX					0x0010
#define IDD_ABOUTBOX					100
#define IDS_ABOUTBOX					101
#define IDD_MFCVIBEDEMO_DIALOG				102
#define IDD_ETC_STYP					103

// Dialog controls for IDD_ETC_STYP
#define IDC_WG_CMD_STATIC0				1000
#define IDC_ETC_PC_ST_3D				1001
#define IDC_ETC_PC_ST_XZ				1002
#define IDC_ETC_PC_ST_YZ				1003
#define IDC_ETC_PC_ST_XY				1004
#define IDC_ETC_PC_ST_RZ				1005
#define IDC_WG_CMD_STATIC1				1006
#define IDC_ETC_PC_MASS_TYPE2			1007
#define IDC_ETC_PC_CONSIDER_OFFSET_CHK	1008
#define IDC_ETC_CONSIDER_ROT_RIGID_MPF_CHK	1009
#define IDC_ETC_PC_MASS_TYPE3			1010
#define IDC_ETC_PC_CONVERT_SELFWEIGHT_CHK	1011
#define IDC_ETC_PC_STRUCT_MASS			1012
#define IDC_ETC_PC_STRUCT_MASS2			1013
#define IDC_ETC_PC_STRUCT_MASS3			1014
#define IDC_WG_CMD_STATIC2				1015
#define IDC_ETC_PC_GRAV					1016
#define IDC_ETC_PC_GRAV_UNIT			1017
#define IDC_WG_CMD_STATIC3				1018
#define IDC_ETC_PC_TEMP					1019
#define IDC_ETC_PC_TEMP_UNIT			1020
#define IDC_ETC_PC_ALIGN_BEAM_CHK		1021
#define IDC_ETC_PC_ALIGN_SLAB_CHK		1022

// 다음은 새 개체에 사용할 기본값입니다.
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE	130
#define _APS_NEXT_CONTROL_VALUE		1023
#define _APS_NEXT_SYMED_VALUE		101
#define _APS_NEXT_COMMAND_VALUE		32771
#endif
#endif
